# Generated by Django 4.2.4 on 2023-10-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='Статус пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verificated',
            field=models.BooleanField(default=False, verbose_name='Подтверждение почты'),
        ),
    ]
