# Generated by Django 4.2.4 on 2023-10-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmaterial_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmaterial',
            name='slug',
            field=models.SlugField(max_length=150, verbose_name='slug'),
        ),
    ]
