# Generated by Django 4.2.4 on 2023-10-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='наименование'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(unique=True, verbose_name='номер версии')),
                ('name', models.CharField(max_length=150, verbose_name='название версии')),
                ('is_active', models.BooleanField(default=False, verbose_name='признак текущей версии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.product', to_field='name', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
            },
        ),
    ]
