# Generated by Django 4.2.4 on 2023-10-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_name_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='num',
            field=models.PositiveIntegerField(verbose_name='номер версии'),
        ),
    ]
